Add Device Code Client for Python
resim-ai/open-core pull request #68
Opened 2023-11-03 20:30 UTC by mikebauer

## Description of change
Add a DeviceCodeClient for python to enable python users to authenticate and use our API.

## Guide to reproduce test results.
```bash
bazel test //resim/auth/python:device_code_client_test
```
## Checklist:
- [x] I have self-reviewed this change.
- [x] I have tested this change.
- [x] This change is covered by tests that are already landed, or in this PR.

2023-11-03 20:32 UTC, mikebauer commented on requirements_lock.txt
> -numba==0.57.1
I sorted this file so all of these are still in here. The new ones are:
```
certifi==2023.7.22
charset-normalizer==3.3.2
idna==3.4
polling2==0.5.0
requests==2.31.0
urllib3==2.0.7
```

2023-11-06 10:44 UTC, benabineri requested changes
Not sure where this is expected to get the client ID from in normal use, but it should default to `gTp1Y0kOyQ7QzIo2lZm0auGM6FJZZVvy`

2023-11-06 17:30 UTC, mikebauer commented
> Not sure where this is expected to get the client ID from in normal use, but it should default to `gTp1Y0kOyQ7QzIo2lZm0auGM6FJZZVvy`

I was expecting users to pass that in (i.e. this client would be pretty generic), but I agree that it seems very reasonable to have that as a default value especially given the other things we're defaulting. Fixing this.

2023-11-06 17:33 UTC, benabineri approved these changes

2023-11-06 18:24 UTC, merged